version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      nextjs-and-react:
        patterns:
          - "next"
          - "react"
          - "react-dom"
          - "@next/*"
        update-types:
          - "minor"
          - "patch"
      tooling:
        patterns:
          - "@biomejs/*"
          - "eslint*"
          - "typescript"
          - "@types/*"
          - "tailwindcss"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
